version: '3.4'

services:
  website:
    image: ${DOCKER_REGISTRY}website
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"